module Docs
	class Perl
		class EntriesFilter < Docs::EntriesFilter
			TYPE_MAP = {
				'perl' => 'Overview',
				'perlintro' => 'Overview',
				'perlrun' => 'Overview',
				'perlreftut' => 'Tutorials',
				'perldsc' => 'Tutorials',
				'perllol' => 'Tutorials',
				'perlrequick' => 'Tutorials',
				'perlretut' => 'Tutorials',
				'perlootut' => 'Tutorials',
				'perlperf' => 'Tutorials',
				'perlstyle' => 'Tutorials',
				'perlcheat' => 'Tutorials',
				'perltrap' => 'Tutorials',
				'perldebtut' => 'Tutorials',
				'perlfaq' => 'Tutorials',
				'perlfaq1' => 'Tutorials',
				'perlfaq2' => 'Tutorials',
				'perlfaq3' => 'Tutorials',
				'perlfaq4' => 'Tutorials',
				'perlfaq5' => 'Tutorials',
				'perlfaq6' => 'Tutorials',
				'perlfaq7' => 'Tutorials',
				'perlfaq8' => 'Tutorials',
				'perlfaq9' => 'Tutorials',
				'perlsyn' => 'Reference Manual',
				'perldata' => 'Reference Manual',
				'perlop' => 'Reference Manual',
				'perlsub' => 'Reference Manual',
				'perlfunc' => 'Reference Manual',
				'perlopentut' => 'Reference Manual',
				'perlpacktut' => 'Reference Manual',
				'perlpod' => 'Reference Manual',
				'perlpodspec' => 'Reference Manual',
				'perlpodstyle' => 'Reference Manual',
				'perldiag' => 'Reference Manual',
				'perllexwarn' => 'Reference Manual',
				'perldebug' => 'Reference Manual',
				'perlvar' => 'Reference Manual',
				'perlre' => 'Reference Manual',
				'perlrebackslash' => 'Reference Manual',
				'perlrecharclass' => 'Reference Manual',
				'perlreref' => 'Reference Manual',
				'perlref' => 'Reference Manual',
				'perlform' => 'Reference Manual',
				'perlobj' => 'Reference Manual',
				'perltie' => 'Reference Manual',
				'perldbmfilter' => 'Reference Manual',
				'perlipc' => 'Reference Manual',
				'perlfork' => 'Reference Manual',
				'perlnumber' => 'Reference Manual',
				'perlthrtut' => 'Reference Manual',
				'perlport' => 'Reference Manual',
				'perllocale' => 'Reference Manual',
				'perluniintro' => 'Reference Manual',
				'perlunicode' => 'Reference Manual',
				'perlunicook' => 'Reference Manual',
				'perlunifaq' => 'Reference Manual',
				'perluniprops' => 'Reference Manual',
				'perlunitut' => 'Reference Manual',
				'perlebcdic' => 'Reference Manual',
				'perlsec' => 'Reference Manual',
				'perlmod' => 'Reference Manual',
				'perlmodlib' => 'Reference Manual',
				'perlmodstyle' => 'Reference Manual',
				'perlmodinstall' => 'Reference Manual',
				'perlnewmod' => 'Reference Manual',
				'perlpragma' => 'Reference Manual',
				'perlutil' => 'Reference Manual',
				'perlfilter' => 'Reference Manual',
				'perldtrace' => 'Reference Manual',
				'perlglossary' => 'Reference Manual',
				'perlembed' => 'Internals and C Language Interface',
				'perldebguts' => 'Internals and C Language Interface',
				'perlxstut' => 'Internals and C Language Interface',
				'perlxs' => 'Internals and C Language Interface',
				'perlxstypemap' => 'Internals and C Language Interface',
				'perlclib' => 'Internals and C Language Interface',
				'perlguts' => 'Internals and C Language Interface',
				'perlcall' => 'Internals and C Language Interface',
				'perlmroapi' => 'Internals and C Language Interface',
				'perlreapi' => 'Internals and C Language Interface',
				'perlreguts' => 'Internals and C Language Interface',
				'perlapi' => 'Internals and C Language Interface',
				'perlintern' => 'Internals and C Language Interface',
				'perliol' => 'Internals and C Language Interface',
				'perlapio' => 'Internals and C Language Interface',
				'perlhack' => 'Internals and C Language Interface',
				'perlsource' => 'Internals and C Language Interface',
				'perlinterp' => 'Internals and C Language Interface',
				'perlhacktut' => 'Internals and C Language Interface',
				'perlhacktips' => 'Internals and C Language Interface',
				'perlpolicy' => 'Internals and C Language Interface',
				'perlgit' => 'Internals and C Language Interface',
				'perlbook' => 'Miscellaneous',
				'perlcommunity' => 'Miscellaneous',
				'perldoc' => 'Miscellaneous',
				'perlhist' => 'Miscellaneous',
				'perldelta' => 'Miscellaneous',
				'perl52111delta' => 'Miscellaneous',
				'perl52110delta' => 'Miscellaneous',
				'perl5219delta' => 'Miscellaneous',
				'perl5218delta' => 'Miscellaneous',
				'perl5217delta' => 'Miscellaneous',
				'perl5216delta' => 'Miscellaneous',
				'perl5215delta' => 'Miscellaneous',
				'perl5214delta' => 'Miscellaneous',
				'perl5213delta' => 'Miscellaneous',
				'perl5212delta' => 'Miscellaneous',
				'perl5211delta' => 'Miscellaneous',
				'perl5210delta' => 'Miscellaneous',
				'perl5202delta' => 'Miscellaneous',
				'perl5201delta' => 'Miscellaneous',
				'perl5200delta' => 'Miscellaneous',
				'perl5184delta' => 'Miscellaneous',
				'perl5182delta' => 'Miscellaneous',
				'perl5181delta' => 'Miscellaneous',
				'perl5180delta' => 'Miscellaneous',
				'perl5163delta' => 'Miscellaneous',
				'perl5162delta' => 'Miscellaneous',
				'perl5161delta' => 'Miscellaneous',
				'perl5160delta' => 'Miscellaneous',
				'perl5144delta' => 'Miscellaneous',
				'perl5143delta' => 'Miscellaneous',
				'perl5142delta' => 'Miscellaneous',
				'perl5141delta' => 'Miscellaneous',
				'perl5140delta' => 'Miscellaneous',
				'perl5125delta' => 'Miscellaneous',
				'perl5124delta' => 'Miscellaneous',
				'perl5123delta' => 'Miscellaneous',
				'perl5122delta' => 'Miscellaneous',
				'perl5121delta' => 'Miscellaneous',
				'perl5120delta' => 'Miscellaneous',
				'perl5101delta' => 'Miscellaneous',
				'perl5100delta' => 'Miscellaneous',
				'perl589delta' => 'Miscellaneous',
				'perl588delta' => 'Miscellaneous',
				'perl587delta' => 'Miscellaneous',
				'perl586delta' => 'Miscellaneous',
				'perl585delta' => 'Miscellaneous',
				'perl584delta' => 'Miscellaneous',
				'perl583delta' => 'Miscellaneous',
				'perl582delta' => 'Miscellaneous',
				'perl581delta' => 'Miscellaneous',
				'perl58delta' => 'Miscellaneous',
				'perl561delta' => 'Miscellaneous',
				'perl56delta' => 'Miscellaneous',
				'perl5005delta' => 'Miscellaneous',
				'perl5004delta' => 'Miscellaneous',
				'perlexperiment' => 'Miscellaneous',
				'perlartistic' => 'Miscellaneous',
				'perlgpl' => 'Miscellaneous',
				'perlcn' => 'Language-Specific',
				'perljp' => 'Language-Specific',
				'perlko' => 'Language-Specific',
				'perltw' => 'Language-Specific',
				'perlaix' => 'Platform-Specific',
				'perlamiga' => 'Platform-Specific',
				'perlandroid' => 'Platform-Specific',
				'perlbs2000' => 'Platform-Specific',
				'perlce' => 'Platform-Specific',
				'perlcygwin' => 'Platform-Specific',
				'perldos' => 'Platform-Specific',
				'perlfreebsd' => 'Platform-Specific',
				'perlhaiku' => 'Platform-Specific',
				'perlhpux' => 'Platform-Specific',
				'perlhurd' => 'Platform-Specific',
				'perlirix' => 'Platform-Specific',
				'perllinux' => 'Platform-Specific',
				'perlmacos' => 'Platform-Specific',
				'perlmacosx' => 'Platform-Specific',
				'perlnetware' => 'Platform-Specific',
				'perlopenbsd' => 'Platform-Specific',
				'perlos2' => 'Platform-Specific',
				'perlos390' => 'Platform-Specific',
				'perlos400' => 'Platform-Specific',
				'perlplan9' => 'Platform-Specific',
				'perlqnx' => 'Platform-Specific',
				'perlriscos' => 'Platform-Specific',
				'perlsolaris' => 'Platform-Specific',
				'perlsymbian' => 'Platform-Specific',
				'perlsynology' => 'Platform-Specific',
				'perltru64' => 'Platform-Specific',
				'perlvms' => 'Platform-Specific',
				'perlvos' => 'Platform-Specific',
				'perlwin32' => 'Platform-Specific',

			}

			def get_name
				node = at_css('h1')
				result = node.content.strip

				result

			end

			def get_type
				return "Built-in Functions" if slug.split('/').first == 'functions'
				return "Changes" if slug.end_with?('delta')

				if TYPE_MAP.has_key?(slug)
					return TYPE_MAP[slug]
				end

				# this should be looking at the TYPE_MAP to decide which section of the manual
				return "Reference Manual" if slug.start_with?("perl")

				# if it wasn't caught yet, it's probably a core module (those are mixed in with the rest)
				return "Core Modules"
			end

		end
	end
end
